// Catálogo de razas.
//
// Es una lista larga (354) y en inglés, así que no sirve como select de
// scroll: el campo de raza es un combo que filtra al escribir. `busqueda`
// guarda cómo se le dice a la raza en el rancho ("charolés", "cara blanca",
// "cebú") para que aparezca sin escribir el nombre oficial.
//
// La raza sigue siendo texto libre en la base: lo que no esté aquí se puede
// capturar igual y se guarda tal cual.

export type Raza = {
  nombre: string;
  /** Sinónimos en español y términos por los que también se encuentra. */
  busqueda?: string;
};

export const RAZAS: Raza[] = [
  { nombre: "ABeef Composite" },
  { nombre: "Aberdeen Angus", busqueda: "angus aberdeen" },
  { nombre: "Aberdeen Angus Cross", busqueda: "cruza" },
  { nombre: "Africander", busqueda: "africander afrikaner" },
  { nombre: "Akaushi", busqueda: "akaushi wagyu rojo japones" },
  { nombre: "Angler Rotvieh" },
  { nombre: "Angler Rotvieh Cross", busqueda: "cruza" },
  { nombre: "Angus", busqueda: "angus" },
  { nombre: "Angus Lowline", busqueda: "angus lowline" },
  { nombre: "Angus Lowline X", busqueda: "cruza" },
  { nombre: "Angus x", busqueda: "cruza" },
  { nombre: "Angus x Florida Cracker", busqueda: "cruza" },
  { nombre: "Angus x Hereford", busqueda: "cruza" },
  { nombre: "Angus x Limousin", busqueda: "cruza" },
  { nombre: "Angus x Salers", busqueda: "cruza" },
  { nombre: "Angus x Wagyu", busqueda: "cruza" },
  { nombre: "Ankole", busqueda: "ankole watusi" },
  { nombre: "Ankole Boran Cross", busqueda: "cruza" },
  { nombre: "Armoricaine" },
  { nombre: "Armoricaine Cross", busqueda: "cruza" },
  { nombre: "Aubrac" },
  { nombre: "Australian Friesian Sahiwal" },
  { nombre: "Australian Illawarra Shorthorn" },
  { nombre: "Australian Lowline" },
  { nombre: "Australian Lowline Cross", busqueda: "cruza" },
  { nombre: "Australian Milking Zebu" },
  { nombre: "Australian Red" },
  { nombre: "Australis South Devon/Angus" },
  { nombre: "Ayrshire", busqueda: "ayrshire" },
  { nombre: "Ayrshire Cross", busqueda: "cruza" },
  { nombre: "Ayshire" },
  { nombre: "Balancer" },
  { nombre: "Baltata Romaneasca" },
  { nombre: "Barzona (Composite)" },
  { nombre: "Baseliner Composite" },
  { nombre: "Baseliner Max Composite" },
  { nombre: "Baseliner X", busqueda: "cruza" },
  { nombre: "Bazadaise" },
  { nombre: "Bazadaise Cross", busqueda: "cruza" },
  { nombre: "Bazadiaz" },
  { nombre: "Beef Shorthorn", busqueda: "shorthorn de carne" },
  { nombre: "Beef Shorthorn Cross", busqueda: "cruza" },
  { nombre: "Beefalo", busqueda: "beefalo" },
  { nombre: "Beefmaker" },
  { nombre: "Beefmaster", busqueda: "beefmaster" },
  { nombre: "Beefmaster X", busqueda: "cruza" },
  { nombre: "Belgian Blue", busqueda: "azul belga" },
  { nombre: "Belmont Red", busqueda: "belmont rojo" },
  { nombre: "Belted Galloway", busqueda: "galloway cinchado" },
  { nombre: "Belted Galloway Cross", busqueda: "cruza" },
  { nombre: "Belted Welsh Black" },
  { nombre: "Belted Welsh Black Cross", busqueda: "cruza" },
  { nombre: "Bison", busqueda: "bisonte bufalo americano" },
  { nombre: "Black Angus", busqueda: "angus negro" },
  { nombre: "Black Baldy", busqueda: "cara blanca negro baldy" },
  { nombre: "Black Simmental" },
  { nombre: "Black Wagyu", busqueda: "wagyu negro" },
  { nombre: "Blonde d'Aquitaine", busqueda: "rubia de aquitania blonde aquitaine" },
  { nombre: "Blonde D'Aquitaine Cross", busqueda: "cruza" },
  { nombre: "Blue Albion" },
  { nombre: "Blue Albion Cross", busqueda: "cruza" },
  { nombre: "Blue Grey" },
  { nombre: "Blue Grey Cross", busqueda: "cruza" },
  { nombre: "Bonsmara", busqueda: "bonsmara" },
  { nombre: "Boran", busqueda: "boran" },
  { nombre: "Bovelder" },
  { nombre: "Braford", busqueda: "braford" },
  { nombre: "Braford X", busqueda: "cruza" },
  { nombre: "Brahman", busqueda: "brahman brahma cebu" },
  { nombre: "Brahman Angus X", busqueda: "cruza" },
  { nombre: "Brahman Cross", busqueda: "cruza" },
  { nombre: "Brahman x", busqueda: "cruza" },
  { nombre: "Brahman x Florida Cracker", busqueda: "cruza" },
  { nombre: "Brahmousin", busqueda: "brahmousin" },
  { nombre: "Braler" },
  { nombre: "Bramalow" },
  { nombre: "Brangus", busqueda: "brangus" },
  { nombre: "Brangus X", busqueda: "cruza" },
  { nombre: "Braunvieh", busqueda: "braunvieh pardo suizo" },
  { nombre: "Bretonne Pie-Noire" },
  { nombre: "Bretonne Pie-Noire Cross", busqueda: "cruza" },
  { nombre: "British Blue Cross", busqueda: "cruza" },
  { nombre: "British Blue", busqueda: "azul britanico" },
  { nombre: "British Friesian", busqueda: "frisona britanica" },
  { nombre: "British Friesian Cross", busqueda: "cruza" },
  { nombre: "British White" },
  { nombre: "British White Cross", busqueda: "cruza" },
  { nombre: "Brown Swiss", busqueda: "suizo pardo" },
  { nombre: "Brown Swiss Cross", busqueda: "cruza" },
  { nombre: "Buffalo", busqueda: "bufalo" },
  { nombre: "Charbray", busqueda: "charbray" },
  { nombre: "Charolais", busqueda: "charolais charoles" },
  { nombre: "Charolais Cross", busqueda: "cruza" },
  { nombre: "Charolais x Angus", busqueda: "cruza" },
  { nombre: "Chiangus" },
  { nombre: "Chianina", busqueda: "chianina" },
  { nombre: "Chianina Cross", busqueda: "cruza" },
  { nombre: "Chillingham" },
  { nombre: "Chillingham Cross", busqueda: "cruza" },
  { nombre: "Clifford" },
  { nombre: "Corriente", busqueda: "corriente criollo" },
  { nombre: "Criollo", busqueda: "criollo" },
  { nombre: "Criollo Angus X", busqueda: "cruza" },
  { nombre: "Criollo Brahman X", busqueda: "cruza" },
  { nombre: "Criollo Red Angus X", busqueda: "cruza" },
  { nombre: "Criollo X", busqueda: "cruza" },
  { nombre: "Cross Breed Beef", busqueda: "cruza de carne" },
  { nombre: "Cross Breed Dairy", busqueda: "cruza de leche" },
  { nombre: "Dairy Cross", busqueda: "cruza de leche" },
  { nombre: "Dairy Shorthorn", busqueda: "shorthorn de leche" },
  { nombre: "Dairy Shorthorn Cross", busqueda: "cruza" },
  { nombre: "Danish Red" },
  { nombre: "Danish Red Cross", busqueda: "cruza" },
  { nombre: "Devon", busqueda: "devon" },
  { nombre: "Devon Red" },
  { nombre: "Devon Red Cross", busqueda: "cruza" },
  { nombre: "Dexter", busqueda: "dexter" },
  { nombre: "Dexter Cross", busqueda: "cruza" },
  { nombre: "Drakensberger" },
  { nombre: "Drakensberger X", busqueda: "cruza" },
  { nombre: "Droughtmaster", busqueda: "droughtmaster" },
  { nombre: "Droughtmaster x", busqueda: "cruza" },
  { nombre: "Durham" },
  { nombre: "Dwarf Zebu", busqueda: "cebu enano" },
  { nombre: "East Finnish Brown" },
  { nombre: "East Finnish Brown Cross", busqueda: "cruza" },
  { nombre: "Elk (Wapiti)", busqueda: "wapiti alce venado" },
  { nombre: "English Longhorn", busqueda: "longhorn ingles" },
  { nombre: "English Park" },
  { nombre: "English Park Cross", busqueda: "cruza" },
  { nombre: "Estonian Red" },
  { nombre: "Estonian Red Cross", busqueda: "cruza" },
  { nombre: "European Fallow deer", busqueda: "gamo venado" },
  { nombre: "European red deer", busqueda: "ciervo rojo venado" },
  { nombre: "F1" },
  { nombre: "F1 Braford" },
  { nombre: "F1 Braford X", busqueda: "cruza" },
  { nombre: "F1 Brangus" },
  { nombre: "F1 Brangus X", busqueda: "cruza" },
  { nombre: "F2" },
  { nombre: "F3" },
  { nombre: "Flekvieh" },
  { nombre: "Flekvieh Cross", busqueda: "cruza" },
  { nombre: "Florida Cracker", busqueda: "florida cracker criollo" },
  { nombre: "Florida Cracker X", busqueda: "cruza" },
  { nombre: "Fresian" },
  { nombre: "Friesian", busqueda: "frisona holandesa" },
  { nombre: "Friesian (Holstein)", busqueda: "frisona holandesa" },
  { nombre: "Frisona Espagola" },
  { nombre: "Frisona Espagola Cross", busqueda: "cruza" },
  { nombre: "Galloway", busqueda: "galloway" },
  { nombre: "Galloway (including Belted)" },
  { nombre: "Galloway Cross", busqueda: "cruza" },
  { nombre: "Gasconne" },
  { nombre: "Gasconne Crpss" },
  { nombre: "Gayal", busqueda: "gayal" },
  { nombre: "Gelbray" },
  { nombre: "Gelbvieh", busqueda: "gelbvieh" },
  { nombre: "Gelbvieh Cross", busqueda: "cruza" },
  { nombre: "Gloucester" },
  { nombre: "Gloucester Cross", busqueda: "cruza" },
  { nombre: "Greyman" },
  { nombre: "Groninger Blaarkop" },
  { nombre: "Groninger Blaarkop Cross", busqueda: "cruza" },
  { nombre: "Guernsey", busqueda: "guernsey" },
  { nombre: "Guernsey Cross", busqueda: "cruza" },
  { nombre: "Hayes Converter" },
  { nombre: "Hereford", busqueda: "hereford cara blanca" },
  { nombre: "Hereford Cross", busqueda: "cruza" },
  { nombre: "Hereford x Friesian", busqueda: "cruza" },
  { nombre: "Hereford x Santa Gertrudis", busqueda: "cruza" },
  { nombre: "Highland", busqueda: "highland escoces" },
  { nombre: "Highland Cross", busqueda: "cruza" },
  { nombre: "Holstein", busqueda: "holstein holandesa" },
  { nombre: "Holstein Cross", busqueda: "cruza" },
  { nombre: "Holstein Friesian", busqueda: "holstein friesian holandesa" },
  { nombre: "Holstein Friesian Cross", busqueda: "cruza" },
  { nombre: "Horned Hereford", busqueda: "hereford con cuernos cara blanca" },
  { nombre: "Irish Moiled" },
  { nombre: "Irish Moiled Cross", busqueda: "cruza" },
  { nombre: "Jersey", busqueda: "jersey" },
  { nombre: "Jersey Cross", busqueda: "cruza" },
  { nombre: "Kerry" },
  { nombre: "Kerry Cross", busqueda: "cruza" },
  { nombre: "LeanBos" },
  { nombre: "Lim x Sim", busqueda: "cruza" },
  { nombre: "Limousin", busqueda: "limousin limosin" },
  { nombre: "Limousin Cross", busqueda: "cruza" },
  { nombre: "Lincoln Red" },
  { nombre: "Lincoln Red Cross", busqueda: "cruza" },
  { nombre: "Longhorn", busqueda: "longhorn cuernos largos" },
  { nombre: "Longhorn (Texas)", busqueda: "longhorn texano cuernos largos" },
  { nombre: "Longhorn Cross", busqueda: "cruza" },
  { nombre: "Lowline" },
  { nombre: "Luing" },
  { nombre: "Luing Cross", busqueda: "cruza" },
  { nombre: "Maine Anjou" },
  { nombre: "Maine Anjou Cross", busqueda: "cruza" },
  { nombre: "Malkekorthorn" },
  { nombre: "Malkekorthorn Cross", busqueda: "cruza" },
  { nombre: "Mandalong Special" },
  { nombre: "Marchigiana", busqueda: "marchigiana" },
  { nombre: "Marchigiana Cross", busqueda: "cruza" },
  { nombre: "Mashona" },
  { nombre: "Mesopotamian" },
  { nombre: "Meuse Rhine Issel" },
  { nombre: "Meuse Rhine Issel Cross", busqueda: "cruza" },
  { nombre: "MGXH" },
  { nombre: "Milking Short Horn" },
  { nombre: "Milking Shorthorn" },
  { nombre: "Mixed", busqueda: "mezclada mixta cruza revuelta" },
  { nombre: "Montbeliarde", busqueda: "montbeliarda" },
  { nombre: "Muese-Rhine-Issel" },
  { nombre: "Murray Grey", busqueda: "murray grey" },
  { nombre: "Murray Grey Cross", busqueda: "cruza" },
  { nombre: "Murray Grey x Angus", busqueda: "cruza" },
  { nombre: "Murray Grey x Hereford", busqueda: "cruza" },
  { nombre: "Murray Grey x Jersey", busqueda: "cruza" },
  { nombre: "Murray Grey x Shorthorn", busqueda: "cruza" },
  { nombre: "Nelore", busqueda: "nelore" },
  { nombre: "Nelore Angus X", busqueda: "cruza" },
  { nombre: "Nguni", busqueda: "nguni" },
  { nombre: "Normande", busqueda: "normanda" },
  { nombre: "Normande Cross", busqueda: "cruza" },
  { nombre: "Northern Dairy Shorthorn" },
  { nombre: "Norwegian Red" },
  { nombre: "Norwegian Red Cross", busqueda: "cruza" },
  { nombre: "Old English" },
  { nombre: "Old English Cross", busqueda: "cruza" },
  { nombre: "Other", busqueda: "otra otro" },
  { nombre: "Other Dairy", busqueda: "otra de leche" },
  { nombre: "Parthenais" },
  { nombre: "Parthenais Cross", busqueda: "cruza" },
  { nombre: "Pere David's deer", busqueda: "venado pere david" },
  { nombre: "Pie" },
  { nombre: "Piedmontese", busqueda: "piamontes piedmontese" },
  { nombre: "Piemontese", busqueda: "piamontes piemontese" },
  { nombre: "Piemontese Cross", busqueda: "cruza" },
  { nombre: "Pinzgauer", busqueda: "pinzgauer" },
  { nombre: "Pinzgauer Cross", busqueda: "cruza" },
  { nombre: "Poll Charolais", busqueda: "charoles mocho" },
  { nombre: "Poll Devon" },
  { nombre: "Poll Hereford", busqueda: "hereford mocho cara blanca" },
  { nombre: "Poll Shorthorn" },
  { nombre: "Poll Simmental", busqueda: "simmental mocho" },
  { nombre: "Popplewell Composite" },
  { nombre: "Red & White Holstein" },
  { nombre: "Red Angus", busqueda: "angus rojo" },
  { nombre: "Red Baldy", busqueda: "cara blanca colorado baldy" },
  { nombre: "Red Brangus" },
  { nombre: "Red Composite" },
  { nombre: "Red Poll", busqueda: "red poll rojo mocho" },
  { nombre: "Red Poll Cross", busqueda: "cruza" },
  { nombre: "Red Sangus" },
  { nombre: "Red Sindhi", busqueda: "sindhi rojo" },
  { nombre: "Red Wagyu", busqueda: "wagyu rojo akaushi" },
  { nombre: "Reggiana" },
  { nombre: "Reggiana Cross", busqueda: "cruza" },
  { nombre: "Riggit Galloway" },
  { nombre: "Riggit Galloway Cross", busqueda: "cruza" },
  { nombre: "River Buffalo", busqueda: "bufalo de rio" },
  { nombre: "Romagnola", busqueda: "romagnola romanola" },
  { nombre: "Romagnola Cross", busqueda: "cruza" },
  { nombre: "Rotbut" },
  { nombre: "Rotebunde" },
  { nombre: "Rotebunde Cross", busqueda: "cruza" },
  { nombre: "Rouge Flamande" },
  { nombre: "Rouge Flamande Cross", busqueda: "cruza" },
  { nombre: "Rubia Gallega", busqueda: "rubia gallega" },
  { nombre: "Rusa deer (Sundar Samba)", busqueda: "venado rusa" },
  { nombre: "Sahiwal", busqueda: "sahiwal" },
  { nombre: "Sahiwal-Shorthorn" },
  { nombre: "Salers", busqueda: "salers" },
  { nombre: "Salers Cross", busqueda: "cruza" },
  { nombre: "Sambar", busqueda: "venado sambar" },
  { nombre: "Sangus" },
  { nombre: "Santa Gertrudis", busqueda: "santa gertrudis" },
  { nombre: "Senepol", busqueda: "senepol" },
  { nombre: "Shaver Beefblend" },
  { nombre: "Shetland" },
  { nombre: "Shetland Cross", busqueda: "cruza" },
  { nombre: "Shorthorn", busqueda: "shorthorn cuernos cortos" },
  { nombre: "Shorthorn x", busqueda: "cruza" },
  { nombre: "Shorthorn x Angus", busqueda: "cruza" },
  { nombre: "Shorthorn x Hereford", busqueda: "cruza" },
  { nombre: "Sika", busqueda: "venado sika" },
  { nombre: "Simbrah", busqueda: "simbrah" },
  { nombre: "Simford" },
  { nombre: "Simindicus" },
  { nombre: "Simmental", busqueda: "simmental suizo" },
  { nombre: "Simmental Cross", busqueda: "cruza" },
  { nombre: "Simmental Grey" },
  { nombre: "Simmental x Angus", busqueda: "cruza" },
  { nombre: "South Devon", busqueda: "devon del sur" },
  { nombre: "South Devon Cross", busqueda: "cruza" },
  { nombre: "South Poll" },
  { nombre: "Speckle Park", busqueda: "speckle park pinto" },
  { nombre: "Speckle Park Cross", busqueda: "cruza" },
  { nombre: "Speckleline" },
  { nombre: "Stabilizer" },
  { nombre: "Stabilizer X", busqueda: "cruza" },
  { nombre: "Stabilizer x Baseliner Composite", busqueda: "cruza" },
  { nombre: "Station" },
  { nombre: "Sussex", busqueda: "sussex" },
  { nombre: "Sussex Cross", busqueda: "cruza" },
  { nombre: "Swamp Buffalo", busqueda: "bufalo de pantano" },
  { nombre: "Swedish Red" },
  { nombre: "Swedish Red & White" },
  { nombre: "Swedish Red & White Cross", busqueda: "cruza" },
  { nombre: "Swedish Red Cross", busqueda: "cruza" },
  { nombre: "Swedish Red Polled" },
  { nombre: "Swiss Braunvich" },
  { nombre: "Swiss Braunvich Cross", busqueda: "cruza" },
  { nombre: "Swiss Grey" },
  { nombre: "Swiss Grey Cross", busqueda: "cruza" },
  { nombre: "Swiss Orig Braunvieh" },
  { nombre: "Swiss Orig Braunvieh Cross", busqueda: "cruza" },
  { nombre: "Tarantaise" },
  { nombre: "Tarantaise- Tarina" },
  { nombre: "Tarantaise- Tarina Cross", busqueda: "cruza" },
  { nombre: "Thai (Native)" },
  { nombre: "Tuli", busqueda: "tuli" },
  { nombre: "Tyrone Black" },
  { nombre: "Tyrone Black Cross", busqueda: "cruza" },
  { nombre: "Ultrablack", busqueda: "ultrablack ultranegro" },
  { nombre: "Unknown", busqueda: "desconocida sin raza no se sabe" },
  { nombre: "Valdostana Nera" },
  { nombre: "Valdostana Nera Cross", busqueda: "cruza" },
  { nombre: "Vaynol" },
  { nombre: "Vaynol Cross", busqueda: "cruza" },
  { nombre: "Wagyu", busqueda: "wagyu japones" },
  { nombre: "Wagyu Cross", busqueda: "cruza" },
  { nombre: "Wagyu F1" },
  { nombre: "Wagyu F2" },
  { nombre: "Wagyu F3" },
  { nombre: "Wagyu FB" },
  { nombre: "Wagyu PB" },
  { nombre: "Water Buffalo", busqueda: "bufalo de agua" },
  { nombre: "Watuzi", busqueda: "watusi ankole" },
  { nombre: "Welsh Black", busqueda: "gales negro" },
  { nombre: "Welsh Black Cross", busqueda: "cruza" },
  { nombre: "Welsh White" },
  { nombre: "Welsh White Cross", busqueda: "cruza" },
  { nombre: "Whitbred Shorthorn" },
  { nombre: "Whitbred Shorthorn Cross", busqueda: "cruza" },
  { nombre: "White Galloway" },
  { nombre: "White Galloway Cross", busqueda: "cruza" },
  { nombre: "White Park" },
  { nombre: "White Park Cross", busqueda: "cruza" },
  { nombre: "White-tailed deer", busqueda: "venado cola blanca" },
  { nombre: "Yak", busqueda: "yak" },
  { nombre: "Zebu", busqueda: "cebu zebu" },
  { nombre: "Zebu Ankole Cross", busqueda: "cruza" },
  { nombre: "Zebu Boran Cross", busqueda: "cruza" },
];

/**
 * Opciones para <ComboCampo name="raza">. El valor guardado es el nombre.
 * Se arma una sola vez: son 354 y el formulario re-renderiza a cada tecla.
 */
export const OPCIONES_RAZA: { valor: string; etiqueta: string; busqueda?: string }[] =
  RAZAS.map((r) => ({ valor: r.nombre, etiqueta: r.nombre, busqueda: r.busqueda }));

export function existeRaza(nombre: string | null | undefined): boolean {
  if (!nombre) return false;
  const n = nombre.trim().toLowerCase();
  return RAZAS.some((r) => r.nombre.toLowerCase() === n);
}
